### ISSUE TITLE
New emacs-28 formula causes security software to flag stack pivots from Ruby. 

### ISSUE THREAD

**Issue by dylanjm** [daviderestivo/homebrew-emacs-head#36]
This might not be fixable, but my work computer runs CYLANCE Protect and now reports a ruby coroutine as a "Stack Pivot vulnerability" during the build process and halts the build process. I was able to successfully build using the `emacs@27 --HEAD` formula. 

It's pretty well know that CYLANCE will randomly do this on all sorts of safe software installs, so I'm not sure if it's something that can be directly changed in formula. Although, it is strange that it works for 27. 

Here is the traceback from the build:

```
Traceback (most recent call last):
	19: from /usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
	18: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:259:in `install'
	17: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:259:in `each'
	16: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:261:in `block in install'
	15: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:330:in `install_formula'
	14: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:331:in `install'
	13: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:777:in `build'
	12: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:32:in `safe_fork'
	11: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	10: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `block in safe_fork'
	 9: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `open'
	 8: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:36:in `block (2 levels) in safe_fork'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:36:in `fork'
	 6: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:41:in `block (3 levels) in safe_fork'
	 5: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:789:in `block in build'
	 4: from /usr/local/Homebrew/Library/Homebrew/sandbox.rb:88:in `exec'
	 3: from /usr/local/Homebrew/Library/Homebrew/utils.rb:263:in `safe_system'
	 2: from /usr/local/Homebrew/Library/Homebrew/utils.rb:41:in `system'
	 1: from /usr/local/Homebrew/Library/Homebrew/utils.rb:32:in `_system'
/usr/local/Homebrew/Library/Homebrew/utils.rb:32:in `wait': SIGTERM (SignalException)
	16: from /usr/local/Homebrew/Library/Homebrew/brew.rb:110:in `<main>'
	15: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:259:in `install'
	14: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:259:in `each'
	13: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:261:in `block in install'
	12: from /usr/local/Homebrew/Library/Homebrew/cmd/install.rb:330:in `install_formula'
	11: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:331:in `install'
	10: from /usr/local/Homebrew/Library/Homebrew/formula_installer.rb:777:in `build'
	 9: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:32:in `safe_fork'
	 8: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/tmpdir.rb:93:in `mktmpdir'
	 7: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `block in safe_fork'
	 6: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:33:in `open'
	 5: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:36:in `block (2 levels) in safe_fork'
	 4: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:36:in `fork'
	 3: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:37:in `block (3 levels) in safe_fork'
	 2: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:54:in `rescue in block (3 levels) in safe_fork'
	 1: from /usr/local/Homebrew/Library/Homebrew/utils/fork.rb:54:in `puts'
/usr/local/Homebrew/Library/Homebrew/utils/fork.rb:54:in `write': Broken pipe (Errno::EPIPE)
Traceback (most recent call last):
	24: from /usr/local/Homebrew/Library/Homebrew/build.rb:202:in `<main>'
	23: from /usr/local/Homebrew/Library/Homebrew/build.rb:118:in `install'
	22: from /usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
	21: from /usr/local/Homebrew/Library/Homebrew/build.rb:123:in `block in install'
	20: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1166:in `brew'
	19: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2130:in `stage'
	18: from /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.6.3_2/lib/ruby/2.6.0/forwardable.rb:230:in `stage'
	17: from /usr/local/Homebrew/Library/Homebrew/resource.rb:81:in `stage'
	16: from /usr/local/Homebrew/Library/Homebrew/resource.rb:106:in `unpack'
	15: from /usr/local/Homebrew/Library/Homebrew/resource.rb:196:in `mktemp'
	14: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
	13: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
	12: from /usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
	11: from /usr/local/Homebrew/Library/Homebrew/resource.rb:197:in `block in mktemp'
	10: from /usr/local/Homebrew/Library/Homebrew/resource.rb:111:in `block in unpack'
	 9: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2154:in `block in stage'
	 8: from /usr/local/Homebrew/Library/Homebrew/utils.rb:474:in `with_env'
	 7: from /usr/local/Homebrew/Library/Homebrew/formula.rb:2155:in `block (2 levels) in stage'
	 6: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1173:in `block in brew'
	 5: from /usr/local/Homebrew/Library/Homebrew/build.rb:152:in `block (2 levels) in install'
	 4: from /usr/local/Homebrew/Library/Taps/daviderestivo/homebrew-emacs-head/Formula/emacs-head@28.rb:261:in `install'
	 3: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1951:in `system'
	 2: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1951:in `open'
	 1: from /usr/local/Homebrew/Library/Homebrew/formula.rb:1990:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1990:in `wait': SIGTERM (SignalException)
	2: from /usr/local/Homebrew/Library/Homebrew/build.rb:192:in `<main>'
	1: from /usr/local/Homebrew/Library/Homebrew/build.rb:222:in `rescue in <main>'
```

Like I said, not sure if there is anything we can do. Just thought I'd let you know in-case other users run into this problem.

**Comment by daviderestivo** [comment]
Hi @dylanjm, 

thanks for reporting this ... as you said I'm note sure there's something I can do here I dunno to much about CYLANCE ... but it's nice that you have reported this issue so maybe someone else will be able to provide some hints.

Regards,
Davide

**Comment by dylanjm** [comment]
Hi @daviderestivo, not quite sure what happened, but I am able to build emacs-head@28 now. I'll close this issue. Thanks!

**Comment by daviderestivo** [comment]
Ok thanks for the info ...
